// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "likeIt/domain"

	mock "github.com/stretchr/testify/mock"
)

// BadgeRepository is an autogenerated mock type for the BadgeRepository type
type BadgeRepository struct {
	mock.Mock
}

// FindById provides a mock function with given fields: id
func (_m *BadgeRepository) FindById(id domain.BadgeId) (*domain.Badge, error) {
	ret := _m.Called(id)

	var r0 *domain.Badge
	if rf, ok := ret.Get(0).(func(domain.BadgeId) *domain.Badge); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Badge)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.BadgeId) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: b
func (_m *BadgeRepository) Save(b *domain.Badge) (*domain.Badge, error) {
	ret := _m.Called(b)

	var r0 *domain.Badge
	if rf, ok := ret.Get(0).(func(*domain.Badge) *domain.Badge); ok {
		r0 = rf(b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Badge)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Badge) error); ok {
		r1 = rf(b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
